messages = {

    "welcome": "سلام خوش آمدید!",
    "today_messages": "پیام های امروز",
    "date_filter_messages": "پیام ها براساس تاریخ",
    "get_report": "گزارش گیری",
    "please_enter_date": "لطفا تاریخ مورد نظر خود را وارد کنید",
    "message": "فرستنده: {}\nتاریخ: {}\n\n{}",
    "there_is_no_message": "هیچ پیامی وجود ندارد",
    "summary_all": "خلاصه کل",
    "summary_today": "خلاصه امروز",
    "users_files_retrieval": "بازیابی اکانت های کاربران",
    "users_report": "گزارش کاربران",
    "hosts_report": "گزارش سرورها",
    "choose_your_option": "گزینه مورد نظر خود را انتخاب کنید",
    "all_accounts_count": "تعداد کل اکانت ها",
    "accounts_per_user": "تعداد اکانت های ساخته شده به تفکیک کاربران",
    "accounts_created_today": "تعداد اکانت هایی که امروز ساخته شده اند",
    "enter_username": "نام کاربری مورد نظر را وارد کنید",
    "user_not_found": "کاربر یافت نشد!",
    "host_not_found": "هاست یافت نشد",
    "file_not_found": "فایلی یافت نشد",
    "enter_host_name": "نام هاست را وارد کنید",
    "full_report": "گزارش کامل",
    "filter_by_date":"فیلتر بر اساس تاریخ",
    "filter_by_expiration": "فیلتر براساس تاریخ انقضا",
    "choose_report_type": "چه نوع گزارشی میخواهید؟",
    "please_enter_start_date": "لطفا تاریخ شروع را وارد کنید",
    "please_enter_end_date": "لطفا تاریخ پایان را وارد کنید",
    "please_enter_start_expiration": "لطفا شروع بازه تاریخ انقضا را وارد کنید",
    "please_enter_end_expiration": "لطفا پایان بازه تاریخ انقضا را وارد کنید",
    "try_again": "لطفا مجدد تلاش کنید!",
    "enter_number_of_files": "چند فایل اخیر بازیابی شود؟",
    "account_retrieval": "بازیابی اکانت",
    "back": "بازگشت",
}
